#!/bin/bash
#
# copy this file to /etc/cron.daily/

mv /opt/LinkIT_Dash/log/lastheard.log /opt/LinkIT_Dash/log/lastheard.log.save
/usr/bin/tail -250 /opt/LinkIT_Dash/log/lastheard.log.save > /opt/LinkIT_Dash/log/lastheard.log
mv /opt/LinkIT_Dash/log/lastheard.log /opt/LinkIT_Dash/log/lastheard.log.save
/usr/bin/tail -250 /opt/LinkIT_Dash/log/lastheard.log.save > /opt/LinkIT_Dash/log/lastheard.log
